
apiVersion: v1
kind: Pod
metadata:
  labels:
    name: redis
  name: redis
spec:
  containers:
    - name: redis
      image: redis:3.0.5
      ports:
        - containerPort: 6379
      volumeMounts:
        - mountPath: "/usr/local/etc/"
          name: "redis-conf"

   